# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_flight.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addFlight(object):
    def setupUi(self, addFlight):
        addFlight.setObjectName("addFlight")
        addFlight.resize(512, 809)
        self.label = QtWidgets.QLabel(addFlight)
        self.label.setGeometry(QtCore.QRect(50, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.flightid = QtWidgets.QLineEdit(addFlight)
        self.flightid.setGeometry(QtCore.QRect(220, 40, 231, 31))
        self.flightid.setObjectName("flightid")
        self.reok = QtWidgets.QPushButton(addFlight)
        self.reok.setGeometry(QtCore.QRect(210, 770, 75, 23))
        self.reok.setObjectName("reok")
        self.label_2 = QtWidgets.QLabel(addFlight)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.start = QtWidgets.QLineEdit(addFlight)
        self.start.setGeometry(QtCore.QRect(220, 90, 231, 31))
        self.start.setObjectName("start")
        self.label_3 = QtWidgets.QLabel(addFlight)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.end = QtWidgets.QLineEdit(addFlight)
        self.end.setGeometry(QtCore.QRect(220, 140, 231, 31))
        self.end.setObjectName("end")
        self.label_5 = QtWidgets.QLabel(addFlight)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stime = QtWidgets.QLineEdit(addFlight)
        self.stime.setGeometry(QtCore.QRect(220, 190, 231, 31))
        self.stime.setObjectName("stime")
        self.label_6 = QtWidgets.QLabel(addFlight)
        self.label_6.setGeometry(QtCore.QRect(50, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.etime = QtWidgets.QLineEdit(addFlight)
        self.etime.setGeometry(QtCore.QRect(220, 240, 231, 31))
        self.etime.setObjectName("etime")
        self.label_7 = QtWidgets.QLabel(addFlight)
        self.label_7.setGeometry(QtCore.QRect(50, 290, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.sdate = QtWidgets.QLineEdit(addFlight)
        self.sdate.setGeometry(QtCore.QRect(220, 290, 231, 31))
        self.sdate.setObjectName("sdate")
        self.label_8 = QtWidgets.QLabel(addFlight)
        self.label_8.setGeometry(QtCore.QRect(280, 320, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(addFlight)
        self.label_9.setGeometry(QtCore.QRect(50, 360, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.edate = QtWidgets.QLineEdit(addFlight)
        self.edate.setGeometry(QtCore.QRect(220, 360, 231, 31))
        self.edate.setObjectName("edate")
        self.label_10 = QtWidgets.QLabel(addFlight)
        self.label_10.setGeometry(QtCore.QRect(50, 410, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.fnum = QtWidgets.QLineEdit(addFlight)
        self.fnum.setGeometry(QtCore.QRect(220, 410, 231, 31))
        self.fnum.setObjectName("fnum")
        self.label_11 = QtWidgets.QLabel(addFlight)
        self.label_11.setGeometry(QtCore.QRect(50, 460, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.enum_2 = QtWidgets.QLineEdit(addFlight)
        self.enum_2.setGeometry(QtCore.QRect(220, 460, 231, 31))
        self.enum_2.setObjectName("enum_2")
        self.label_12 = QtWidgets.QLabel(addFlight)
        self.label_12.setGeometry(QtCore.QRect(50, 510, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Bnum = QtWidgets.QLineEdit(addFlight)
        self.Bnum.setGeometry(QtCore.QRect(220, 510, 231, 31))
        self.Bnum.setObjectName("Bnum")
        self.label_13 = QtWidgets.QLabel(addFlight)
        self.label_13.setGeometry(QtCore.QRect(50, 560, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.tflag = QtWidgets.QLineEdit(addFlight)
        self.tflag.setGeometry(QtCore.QRect(220, 560, 231, 31))
        self.tflag.setObjectName("tflag")
        self.label_14 = QtWidgets.QLabel(addFlight)
        self.label_14.setGeometry(QtCore.QRect(50, 610, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Fprice = QtWidgets.QLineEdit(addFlight)
        self.Fprice.setGeometry(QtCore.QRect(220, 610, 231, 31))
        self.Fprice.setObjectName("Fprice")
        self.label_15 = QtWidgets.QLabel(addFlight)
        self.label_15.setGeometry(QtCore.QRect(50, 660, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(addFlight)
        self.label_16.setGeometry(QtCore.QRect(50, 710, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.Bprice = QtWidgets.QLineEdit(addFlight)
        self.Bprice.setGeometry(QtCore.QRect(220, 660, 231, 31))
        self.Bprice.setObjectName("Bprice")
        self.Eprice = QtWidgets.QLineEdit(addFlight)
        self.Eprice.setGeometry(QtCore.QRect(220, 710, 231, 31))
        self.Eprice.setObjectName("Eprice")

        self.retranslateUi(addFlight)
        QtCore.QMetaObject.connectSlotsByName(addFlight)

    def retranslateUi(self, addFlight):
        _translate = QtCore.QCoreApplication.translate
        addFlight.setWindowTitle(_translate("addFlight", "添加"))
        self.label.setText(_translate("addFlight", "请输入航班号"))
        self.reok.setText(_translate("addFlight", "OK"))
        self.label_2.setText(_translate("addFlight", "请输入起飞地点"))
        self.label_3.setText(_translate("addFlight", "请输入目的地"))
        self.label_5.setText(_translate("addFlight", "请输入起飞时间"))
        self.label_6.setText(_translate("addFlight", "请输入落地时间"))
        self.label_7.setText(_translate("addFlight", "请输入起飞日期"))
        self.label_8.setText(_translate("addFlight", "形如xxxx.xx.xx"))
        self.label_9.setText(_translate("addFlight", "请输入落地日期"))
        self.label_10.setText(_translate("addFlight", "头等舱机票数"))
        self.label_11.setText(_translate("addFlight", "经济舱机票数"))
        self.label_12.setText(_translate("addFlight", "商务舱机票数"))
        self.label_13.setText(_translate("addFlight", "机票标志位"))
        self.label_14.setText(_translate("addFlight", "头等舱价格"))
        self.label_15.setText(_translate("addFlight", "商务舱价格"))
        self.label_16.setText(_translate("addFlight", "经济舱机价格"))

