# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'refresh_user.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_refreshUser(object):
    def setupUi(self, refreshUser):
        refreshUser.setObjectName("refreshUser")
        refreshUser.resize(504, 603)
        self.label = QtWidgets.QLabel(refreshUser)
        self.label.setGeometry(QtCore.QRect(50, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.userid = QtWidgets.QLineEdit(refreshUser)
        self.userid.setGeometry(QtCore.QRect(220, 40, 231, 31))
        self.userid.setObjectName("userid")
        self.reok = QtWidgets.QPushButton(refreshUser)
        self.reok.setGeometry(QtCore.QRect(220, 570, 75, 23))
        self.reok.setObjectName("reok")
        self.label_2 = QtWidgets.QLabel(refreshUser)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(refreshUser)
        self.username.setGeometry(QtCore.QRect(220, 90, 231, 31))
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(refreshUser)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.userbirth = QtWidgets.QLineEdit(refreshUser)
        self.userbirth.setGeometry(QtCore.QRect(220, 140, 231, 31))
        self.userbirth.setObjectName("userbirth")
        self.label_4 = QtWidgets.QLabel(refreshUser)
        self.label_4.setGeometry(QtCore.QRect(290, 170, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(refreshUser)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.usersex = QtWidgets.QLineEdit(refreshUser)
        self.usersex.setGeometry(QtCore.QRect(220, 210, 231, 31))
        self.usersex.setObjectName("usersex")
        self.label_6 = QtWidgets.QLabel(refreshUser)
        self.label_6.setGeometry(QtCore.QRect(50, 260, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.usernum = QtWidgets.QLineEdit(refreshUser)
        self.usernum.setGeometry(QtCore.QRect(220, 260, 231, 31))
        self.usernum.setObjectName("usernum")
        self.label_7 = QtWidgets.QLabel(refreshUser)
        self.label_7.setGeometry(QtCore.QRect(50, 310, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.usertype = QtWidgets.QLineEdit(refreshUser)
        self.usertype.setGeometry(QtCore.QRect(220, 310, 231, 31))
        self.usertype.setObjectName("usertype")
        self.label_8 = QtWidgets.QLabel(refreshUser)
        self.label_8.setGeometry(QtCore.QRect(280, 340, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(refreshUser)
        self.label_9.setGeometry(QtCore.QRect(50, 380, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.useridnum = QtWidgets.QLineEdit(refreshUser)
        self.useridnum.setGeometry(QtCore.QRect(220, 380, 231, 31))
        self.useridnum.setObjectName("useridnum")
        self.label_10 = QtWidgets.QLabel(refreshUser)
        self.label_10.setGeometry(QtCore.QRect(50, 440, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.userpay = QtWidgets.QLineEdit(refreshUser)
        self.userpay.setGeometry(QtCore.QRect(220, 440, 231, 31))
        self.userpay.setObjectName("userpay")
        self.label_11 = QtWidgets.QLabel(refreshUser)
        self.label_11.setGeometry(QtCore.QRect(50, 500, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.userpassword = QtWidgets.QLineEdit(refreshUser)
        self.userpassword.setGeometry(QtCore.QRect(220, 500, 231, 31))
        self.userpassword.setObjectName("userpassword")

        self.retranslateUi(refreshUser)
        QtCore.QMetaObject.connectSlotsByName(refreshUser)

    def retranslateUi(self, refreshUser):
        _translate = QtCore.QCoreApplication.translate
        refreshUser.setWindowTitle(_translate("refreshUser", "更新"))
        self.label.setText(_translate("refreshUser", "请输入客户编号"))
        self.reok.setText(_translate("refreshUser", "OK"))
        self.label_2.setText(_translate("refreshUser", "请输入客户姓名"))
        self.label_3.setText(_translate("refreshUser", "请输入出生日期"))
        self.label_4.setText(_translate("refreshUser", "形如（xxxx.xx.xx）"))
        self.label_5.setText(_translate("refreshUser", "请输入性别"))
        self.label_6.setText(_translate("refreshUser", "请输入联系方式"))
        self.label_7.setText(_translate("refreshUser", "请输入证件类型"))
        self.label_8.setText(_translate("refreshUser", "身份证/护照"))
        self.label_9.setText(_translate("refreshUser", "请输入证件号码"))
        self.label_10.setText(_translate("refreshUser", "请输入付款方式"))
        self.label_11.setText(_translate("refreshUser", "请输入客户密码"))

