# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'refresh_flight.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_refreshFlight(object):
    def setupUi(self, refreshFlight):
        refreshFlight.setObjectName("refreshFlight")
        refreshFlight.resize(504, 603)
        self.label = QtWidgets.QLabel(refreshFlight)
        self.label.setGeometry(QtCore.QRect(50, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.flightid = QtWidgets.QLineEdit(refreshFlight)
        self.flightid.setGeometry(QtCore.QRect(220, 40, 231, 31))
        self.flightid.setObjectName("flightid")
        self.reok = QtWidgets.QPushButton(refreshFlight)
        self.reok.setGeometry(QtCore.QRect(220, 570, 75, 23))
        self.reok.setObjectName("reok")
        self.label_2 = QtWidgets.QLabel(refreshFlight)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.start = QtWidgets.QLineEdit(refreshFlight)
        self.start.setGeometry(QtCore.QRect(220, 90, 231, 31))
        self.start.setObjectName("start")
        self.label_3 = QtWidgets.QLabel(refreshFlight)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.end = QtWidgets.QLineEdit(refreshFlight)
        self.end.setGeometry(QtCore.QRect(220, 140, 231, 31))
        self.end.setObjectName("end")
        self.label_5 = QtWidgets.QLabel(refreshFlight)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stime = QtWidgets.QLineEdit(refreshFlight)
        self.stime.setGeometry(QtCore.QRect(220, 190, 231, 31))
        self.stime.setObjectName("stime")
        self.label_6 = QtWidgets.QLabel(refreshFlight)
        self.label_6.setGeometry(QtCore.QRect(50, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.etime = QtWidgets.QLineEdit(refreshFlight)
        self.etime.setGeometry(QtCore.QRect(220, 240, 231, 31))
        self.etime.setObjectName("etime")
        self.label_7 = QtWidgets.QLabel(refreshFlight)
        self.label_7.setGeometry(QtCore.QRect(50, 290, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.sdate = QtWidgets.QLineEdit(refreshFlight)
        self.sdate.setGeometry(QtCore.QRect(220, 290, 231, 31))
        self.sdate.setObjectName("sdate")
        self.label_8 = QtWidgets.QLabel(refreshFlight)
        self.label_8.setGeometry(QtCore.QRect(280, 320, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(refreshFlight)
        self.label_9.setGeometry(QtCore.QRect(50, 360, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.edate = QtWidgets.QLineEdit(refreshFlight)
        self.edate.setGeometry(QtCore.QRect(220, 360, 231, 31))
        self.edate.setObjectName("edate")
        self.label_10 = QtWidgets.QLabel(refreshFlight)
        self.label_10.setGeometry(QtCore.QRect(50, 410, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.fnum = QtWidgets.QLineEdit(refreshFlight)
        self.fnum.setGeometry(QtCore.QRect(220, 410, 231, 31))
        self.fnum.setObjectName("fnum")
        self.label_11 = QtWidgets.QLabel(refreshFlight)
        self.label_11.setGeometry(QtCore.QRect(50, 460, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.enum_2 = QtWidgets.QLineEdit(refreshFlight)
        self.enum_2.setGeometry(QtCore.QRect(220, 460, 231, 31))
        self.enum_2.setObjectName("enum_2")
        self.label_12 = QtWidgets.QLabel(refreshFlight)
        self.label_12.setGeometry(QtCore.QRect(50, 510, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Bnum = QtWidgets.QLineEdit(refreshFlight)
        self.Bnum.setGeometry(QtCore.QRect(220, 510, 231, 31))
        self.Bnum.setObjectName("Bnum")

        self.retranslateUi(refreshFlight)
        QtCore.QMetaObject.connectSlotsByName(refreshFlight)

    def retranslateUi(self, refreshFlight):
        _translate = QtCore.QCoreApplication.translate
        refreshFlight.setWindowTitle(_translate("refreshFlight", "更新"))
        self.label.setText(_translate("refreshFlight", "请输入航班号"))
        self.reok.setText(_translate("refreshFlight", "OK"))
        self.label_2.setText(_translate("refreshFlight", "请输入起飞地点"))
        self.label_3.setText(_translate("refreshFlight", "请输入目的地"))
        self.label_5.setText(_translate("refreshFlight", "请输入起飞时间"))
        self.label_6.setText(_translate("refreshFlight", "请输入落地时间"))
        self.label_7.setText(_translate("refreshFlight", "请输入起飞日期"))
        self.label_8.setText(_translate("refreshFlight", "形如xxxx.xx.xx"))
        self.label_9.setText(_translate("refreshFlight", "请输入落地日期"))
        self.label_10.setText(_translate("refreshFlight", "头等舱机票数"))
        self.label_11.setText(_translate("refreshFlight", "经济舱机票数"))
        self.label_12.setText(_translate("refreshFlight", "商务舱机票数"))

