# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_refreshinfo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_userREFRESH(object):
    def setupUi(self, userREFRESH):
        userREFRESH.setObjectName("userREFRESH")
        userREFRESH.resize(496, 500)
        self.reok = QtWidgets.QPushButton(userREFRESH)
        self.reok.setGeometry(QtCore.QRect(210, 460, 75, 23))
        self.reok.setObjectName("reok")
        self.label_2 = QtWidgets.QLabel(userREFRESH)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(userREFRESH)
        self.username.setGeometry(QtCore.QRect(220, 30, 231, 31))
        self.username.setObjectName("username")
        self.label_3 = QtWidgets.QLabel(userREFRESH)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.userbirth = QtWidgets.QLineEdit(userREFRESH)
        self.userbirth.setGeometry(QtCore.QRect(220, 80, 231, 31))
        self.userbirth.setObjectName("userbirth")
        self.label_4 = QtWidgets.QLabel(userREFRESH)
        self.label_4.setGeometry(QtCore.QRect(290, 110, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(userREFRESH)
        self.label_5.setGeometry(QtCore.QRect(50, 140, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.usersex = QtWidgets.QLineEdit(userREFRESH)
        self.usersex.setGeometry(QtCore.QRect(220, 140, 231, 31))
        self.usersex.setObjectName("usersex")
        self.label_6 = QtWidgets.QLabel(userREFRESH)
        self.label_6.setGeometry(QtCore.QRect(50, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.usernum = QtWidgets.QLineEdit(userREFRESH)
        self.usernum.setGeometry(QtCore.QRect(220, 190, 231, 31))
        self.usernum.setObjectName("usernum")
        self.label_7 = QtWidgets.QLabel(userREFRESH)
        self.label_7.setGeometry(QtCore.QRect(50, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.usertype = QtWidgets.QLineEdit(userREFRESH)
        self.usertype.setGeometry(QtCore.QRect(220, 240, 231, 31))
        self.usertype.setObjectName("usertype")
        self.label_8 = QtWidgets.QLabel(userREFRESH)
        self.label_8.setGeometry(QtCore.QRect(280, 270, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(userREFRESH)
        self.label_9.setGeometry(QtCore.QRect(50, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.useridnum = QtWidgets.QLineEdit(userREFRESH)
        self.useridnum.setGeometry(QtCore.QRect(220, 300, 231, 31))
        self.useridnum.setObjectName("useridnum")
        self.label_10 = QtWidgets.QLabel(userREFRESH)
        self.label_10.setGeometry(QtCore.QRect(50, 350, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.userpay = QtWidgets.QLineEdit(userREFRESH)
        self.userpay.setGeometry(QtCore.QRect(220, 350, 231, 31))
        self.userpay.setObjectName("userpay")
        self.label_11 = QtWidgets.QLabel(userREFRESH)
        self.label_11.setGeometry(QtCore.QRect(50, 400, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.userpassword = QtWidgets.QLineEdit(userREFRESH)
        self.userpassword.setGeometry(QtCore.QRect(220, 400, 231, 31))
        self.userpassword.setObjectName("userpassword")

        self.retranslateUi(userREFRESH)
        QtCore.QMetaObject.connectSlotsByName(userREFRESH)

    def retranslateUi(self, userREFRESH):
        _translate = QtCore.QCoreApplication.translate
        userREFRESH.setWindowTitle(_translate("userREFRESH", "更新"))
        self.reok.setText(_translate("userREFRESH", "OK"))
        self.label_2.setText(_translate("userREFRESH", "请输入客户姓名"))
        self.label_3.setText(_translate("userREFRESH", "请输入出生日期"))
        self.label_4.setText(_translate("userREFRESH", "形如（xxxx.xx.xx）"))
        self.label_5.setText(_translate("userREFRESH", "请输入性别"))
        self.label_6.setText(_translate("userREFRESH", "请输入联系方式"))
        self.label_7.setText(_translate("userREFRESH", "请输入证件类型"))
        self.label_8.setText(_translate("userREFRESH", "身份证/护照"))
        self.label_9.setText(_translate("userREFRESH", "请输入证件号码"))
        self.label_10.setText(_translate("userREFRESH", "请输入付款方式"))
        self.label_11.setText(_translate("userREFRESH", "请输入客户密码"))

